### PR TITLE
Support for newest ESX

### PR DESCRIPTION
**Pull request by userMacieG**
Need to be tested 👍 

For: Day. F

### CODE REVIEW

**Comment by AlexisHodiesne** [comment]
You miss a ) at the end of line 165 in the server side
and i have this:
```
 [91mSCRIPT ERROR: @es_extended/server/classes/player.lua:365: attempt to index a nil value (field ?)[0m
[93m> ref[0m ([36m@es_extended/server/classes/player.lua[0m:365)
[93m> fn[0m ([36m@esx_illegal_drugs/server/esx_illegal_drugs_sv.lua[0m:206)
```
esx_illegal_drugs/server/esx_illegal_drugs_sv.lua LINE 206
`if not xPlayer.canCarryItem(opium, opium.count) then
`
es_extended/server/classes/player.lua LINE 364 to 369
```
self.canCarryItem = function(name, count)
		local currentWeight, itemWeight = self.getWeight(), ESX.Items[name].weight
		local newWeight = currentWeight + (itemWeight * count)

		return newWeight <= self.maxWeight
	end
```

**Comment by userMacieG** [comment]
Fixed 165 line. Try use this now.

**Comment by XxFri3ndlyxX** [comment]
I do not play fivem anymore but if you can assure me it's working i will accept the pull. Let me know.

**Comment by AlexisHodiesne** [comment]
same error with
```

[93m> ref�[0m (�[36m@es_extended/server/classes/player.lua[0m:365)
[93m> fn�[0m (�[36m@esx_illegal_drugs/server/esx_illegal_drugs_sv.lua�[0m:206)
```

**Comment by AlexisHodiesne** [comment]
So not working maybe the opium.count ?

**Comment by AlexisHodiesne** [comment]
Tested with cannabis and same error, all is working but no cannabis in my inventory

**Comment by marciogalvao89** [comment]
FIX:
if not xPlayer.canCarryItem(weed, weed.count) then
to
if not xPlayer.canCarryItem('weed', weed.count) then

if not xPlayer.canCarryItem(coke, weed.count) then
to
if not xPlayer.canCarryItem('coke', weed.count) then

same for meta and opium.

**Comment by AlexisHodiesne** [comment]
nice it s working. One little thing, your character can move when you pickup/process/sell and if you are moving it cancel the process

**Comment by XxFri3ndlyxX** [comment]
@marciogalvao89 Please do a pr and i will accept it. I do not have time right now. 
@DayField It is intended that you can move and that it cancels it when moving. I hated the freezing ped.  This way felt more real. Anyway you can always modify it to your need.

**Comment by AlexisHodiesne** [comment]
Ok so everything is ok you can merge if you want

**Comment by Kraleemil** [comment]
Do any one have FiveMIPL

**Comment by XxFri3ndlyxX** [comment]
> FiveMIPL

Just one google search buddy.....
https://github.com/esx-community/fivem-ipl

**Pull request merged**
